services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASS}
      - SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS=true
    volumes:
      - ./h2_db_files:/app/data